// src/utils/avatarResolver.ts
const avatarMap: Record<string, any> = {
  // mevcut görseller
  'logo1.png': require('../assets/images/logo.webp'),
  'kahve.png': require('../assets/images/kahve.webp'),
  'tarot-card.png': require('../assets/images/tarot-card.webp'),
  'burc-yorum.png': require('../assets/images/burc-yorum.webp'),
  'ruya_rehberi.png': require('../assets/images/ruya_rehberi.webp'),
  'transit.png': require('../assets/images/transit.webp'),
  'starmap.png': require('../assets/images/starmap.webp'),
  'tarot-back.png': require('../assets/images/tarot-back.webp'),
  'default-avatar.png': require('../assets/images/logo.webp'),
  'bakiye': require('../assets/images/bakiye.png'),
  'ask_uyumu.png': require('../assets/images/ask_uyumu.webp'),

  // TAROT (src/assets/image/tarot) — isimler birebir
  '11-tilsim_usagi.png': require('../assets/images/tarot/11-tilsim_usagi.webp'),
  '14-tilsim_krali.png': require('../assets/images/tarot/14-tilsim_krali.webp'),
  '13-tilsim_kralicesi.png': require('../assets/images/tarot/13-tilsim_kralicesi.webp'),
  '12-tilsim_sovalyesi.png': require('../assets/images/tarot/12-tilsim_sovalyesi.webp'),
  '10-on_tilsim.png': require('../assets/images/tarot/10-on_tilsim.webp'),
  '9-dokuz_tilsim.png': require('../assets/images/tarot/9-dokuz_tilsim.webp'),
  '8-sekiz_tilsim.png': require('../assets/images/tarot/8-sekiz_tilsim.webp'),
  '7-yedi_tilsim.png': require('../assets/images/tarot/7-yedi_tilsim.webp'),
  '6-alti_tilsim.png': require('../assets/images/tarot/6-alti_tilsim.webp'),
  '5-bes_tilsim.png': require('../assets/images/tarot/5-bes_tilsim.webp'),
  '4-dort_tilsim.png': require('../assets/images/tarot/4-dort_tilsim.webp'),
  '3-uc_tilsim.png': require('../assets/images/tarot/3-uc_tilsim.webp'),
  '2-iki_tilsim.png': require('../assets/images/tarot/2-iki_tilsim.webp'),
  '1-tilsim_asi.png': require('../assets/images/tarot/1-tilsim_asi.webp'),
  '11-kilic_usagi.png': require('../assets/images/tarot/11-kilic_usagi.webp'),
  '14-kilic_krali.png': require('../assets/images/tarot/14-kilic_krali.webp'),
  '13-kilic_kralicesi.png': require('../assets/images/tarot/13-kilic_kralicesi.webp'),
  '12-kilic_sovalyesi.png': require('../assets/images/tarot/12-kilic_sovalyesi.webp'),
  '10-on_kilic.png': require('../assets/images/tarot/10-on_kilic.webp'),
  '9-dokuz_kilic.png': require('../assets/images/tarot/9-dokuz_kilic.webp'),
  '8-sekiz_kilic.png': require('../assets/images/tarot/8-sekiz_kilic.webp'),
  '7-yedi_kilic.png': require('../assets/images/tarot/7-yedi_kilic.webp'),
  '6-alti_kilic.png': require('../assets/images/tarot/6-alti_kilic.webp'),
  '5-bes_kilic.png': require('../assets/images/tarot/5-bes_kilic.webp'),
  '4-dort_kilic.png': require('../assets/images/tarot/4-dort_kilic.webp'),
  '3-uc_kilic.png': require('../assets/images/tarot/3-uc_kilic.webp'),
  '2-iki_kilic.png': require('../assets/images/tarot/2-iki_kilic.webp'),
  '1-kilic_asi.png': require('../assets/images/tarot/1-kilic_asi.webp'),
  '11-kupa_prensi.png': require('../assets/images/tarot/11-kupa_prensi.webp'),
  '14-kupa_krali.png': require('../assets/images/tarot/14-kupa_krali.webp'),
  '13-kupa_kralicesi.png': require('../assets/images/tarot/13-kupa_kralicesi.webp'),
  '12-kupa_sovalyesi.png': require('../assets/images/tarot/12-kupa_sovalyesi.webp'),
  '10-kupa_onlusu.png': require('../assets/images/tarot/10-kupa_onlusu.webp'),
  '9-kupa_dokuzlusu.png': require('../assets/images/tarot/9-kupa_dokuzlusu.webp'),
  '8-kupa_sekizlisi.png': require('../assets/images/tarot/8-kupa_sekizlisi.webp'),
  '7-kupa_yedilisi.png': require('../assets/images/tarot/7-kupa_yedilisi.webp'),
  '6-kupa_altilisi.png': require('../assets/images/tarot/6-kupa_altilisi.webp'),
  '5-kupa_beslisi.png': require('../assets/images/tarot/5-kupa_beslisi.webp'),
  '4-kupa_dortlusu.png': require('../assets/images/tarot/4-kupa_dortlusu.webp'),
  '3-kupa_uclusu.png': require('../assets/images/tarot/3-kupa_uclusu.webp'),
  '2-kupa_ikilisi.png': require('../assets/images/tarot/2-kupa_ikilisi.webp'),
  '1-kupa_asi.png': require('../assets/images/tarot/1-kupa_asi.webp'),
  '11-degnek_usagi.png': require('../assets/images/tarot/11-degnek_usagi.webp'),
  '14-degnek_krali.png': require('../assets/images/tarot/14-degnek_krali.webp'),
  '13-degnek_kralicesi.png': require('../assets/images/tarot/13-degnek_kralicesi.webp'),
  '12-degnek_sovalyesi.png': require('../assets/images/tarot/12-degnek_sovalyesi.webp'),
  '10-on_degnek.png': require('../assets/images/tarot/10-on_degnek.webp'),
  '9-dokuz_degnek.png': require('../assets/images/tarot/9-dokuz_degnek.webp'),
  '8-sekiz_degnek.png': require('../assets/images/tarot/8-sekiz_degnek.webp'),
  '7-yedi_degnek.png': require('../assets/images/tarot/7-yedi_degnek.webp'),
  '6-alti_degnek.png': require('../assets/images/tarot/6-alti_degnek.webp'),
  '5-bes_degnek.png': require('../assets/images/tarot/5-bes_degnek.webp'),
  '4-dort_degnek.png': require('../assets/images/tarot/4-dort_degnek.webp'),
  '3-uc_degnek.png': require('../assets/images/tarot/3-uc_degnek.webp'),
  '2-iki_degnek.png': require('../assets/images/tarot/2-iki_degnek.webp'),
  '1-degnek_asi.png': require('../assets/images/tarot/1-degnek_asi.webp'),
  '21-dunya.png': require('../assets/images/tarot/21-dunya.webp'),
  '20-yargi.png': require('../assets/images/tarot/20-yargi.webp'),
  '19-gunes.png': require('../assets/images/tarot/19-gunes.webp'),
  '18-ay.png': require('../assets/images/tarot/18-ay.webp'),
  '17-yildiz.png': require('../assets/images/tarot/17-yildiz.webp'),
  '16-kule.png': require('../assets/images/tarot/16-kule.webp'),
  '15-seytan.png': require('../assets/images/tarot/15-seytan.webp'),
  '14-denge.png': require('../assets/images/tarot/14-denge.webp'),
  '13-olum.png': require('../assets/images/tarot/13-olum.webp'),
  '12-asilan_adam.png': require('../assets/images/tarot/12-asilan_adam.webp'),
  '11-adalet.png': require('../assets/images/tarot/11-adalet.webp'),
  '10-kader_carki.png': require('../assets/images/tarot/10-kader_carki.webp'),
  '9-ermis.png': require('../assets/images/tarot/9-ermis.webp'),
  '8-guc.png': require('../assets/images/tarot/8-guc.webp'),
  '7-savas_arabasi.png': require('../assets/images/tarot/7-savas_arabasi.webp'),
  '6-asiklar.png': require('../assets/images/tarot/6-asiklar.webp'),
  '5-basrahip.png': require('../assets/images/tarot/5-basrahip.webp'),
  '4-imparator.png': require('../assets/images/tarot/4-imparator.webp'),
  '3-imparatorice.png': require('../assets/images/tarot/3-imparatorice.webp'),
  '2-bas_rahibe.png': require('../assets/images/tarot/2-bas_rahibe.webp'),
  '1-buyucu.png': require('../assets/images/tarot/1-buyucu.webp'),
  '0-the_fool-aptal.png': require('../assets/images/tarot/0-the_fool-aptal.webp'),

  'akrep': require('../assets/images/burclar/akrep.webp'),
  'aslan': require('../assets/images/burclar/aslan.webp'),
  'aglak': require('../assets/images/burclar/oglak.webp'),
  'koc': require('../assets/images/burclar/koc.webp'),
  'terazi': require('../assets/images/burclar/terazi.webp'),
  'ikizler': require('../assets/images/burclar/ikizler.webp'),
  'boga': require('../assets/images/burclar/boga.webp'),
  'balik': require('../assets/images/burclar/balik.webp'),
  'basak': require('../assets/images/burclar/basak.webp'),
  'kova': require('../assets/images/burclar/kova.webp'),
  'yengec': require('../assets/images/burclar/yengec.webp'),
  'yay': require('../assets/images/burclar/yay.webp'),


  'yalvac.png': require('../assets/images/yorumcular/yalvac.webp'),
  'astro_leyla.png': require('../assets/images/yorumcular/astro_leyla.webp'),
  'ilham_perisi_mira.png': require('../assets/images/yorumcular/ilham_perisi_mira.webp'),
  'kareemjan.png': require('../assets/images/yorumcular/kareemjan.webp'),
  'medyum_nebis.png': require('../assets/images/yorumcular/medyum_nebis.webp'),
  'ruhsar.png': require('../assets/images/yorumcular/ruhsar.webp'),


};

export const resolveAvatar = (fileName: string): any => {
  return avatarMap[fileName] || avatarMap['default-avatar.png'];
};
